# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0-2QSKAcpEQ7CYz64bHQMBI2fQAhr33
"""

from flask import Flask, render_template, request, jsonify
from game_logic import TicTacToe

app = Flask(__name__)
game = TicTacToe()

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/move", methods=["POST"])
def move():
    data = request.json
    row, col = data["row"], data["col"]
    valid_move = game.make_move(row, col)
    response = {
        "board": game.board,
        "winner": game.winner,
        "current_player": game.current_player,
        "is_draw": game.is_draw(),
        "valid_move": valid_move
    }
    return jsonify(response)

@app.route("/reset", methods=["POST"])
def reset():
    game.reset()
    return jsonify({"status": "reset", "board": game.board})

if __name__ == "__main__":
    app.run(debug=True)