# -*- coding: utf-8 -*-
"""game_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0-2QSKAcpEQ7CYz64bHQMBI2fQAhr33
"""

class TicTacToe:
    def __init__(self):
        self.board = [[" " for _ in range(3)] for _ in range(3)]
        self.current_player = "X"
        self.winner = None

    def reset(self):
        self.__init__()

    def make_move(self, row, col):
        if self.board[row][col] == " " and not self.winner:
            self.board[row][col] = self.current_player
            if self.check_winner(row, col):
                self.winner = self.current_player
            self.current_player = "O" if self.current_player == "X" else "X"
            return True
        return False

    def check_winner(self, row, col):
        player = self.board[row][col]
        # Check row, column, and diagonals
        return (
            all(self.board[row][c] == player for c in range(3)) or
            all(self.board[r][col] == player for r in range(3)) or
            all(self.board[i][i] == player for i in range(3)) or
            all(self.board[i][2 - i] == player for i in range(3))
        )

    def is_draw(self):
        return all(self.board[row][col] != " " for row in range(3) for col in range(3)) and not self.winner